In [46]:
import pandas as pd
import numpy as np
import csv
import sqlite3
import re
import pickle

from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, auc

from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
filename_csv = '/Users/xzhou/github/project_files/lending_club/loan.csv'
date_to_parse = ['issue_d' , 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'earliest_cr_line']

df=pd.read_csv(filename_csv, date_parser=date_to_parse)

/Users/xzhou/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.shape

(887379, 74)

In [4]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl',
       'inq_last_12m'],
      dtype='object')

In [ ]:
# filename_sql = '/Users/xzhou/github/project_files/lending_club/database.sqlite'
# # date_to_parse = ['issue_d' , 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'earliest_cr_line']
# conn = sqlite3.connect(filename_sql)

# df = pd.read_sql_query('select * from loan', con=conn, parse_dates = date_to_parse)

In [ ]:
# df.columns

In [5]:
df.rename(index=str, columns={"dti": "payment_to_income_ratio"})

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000.0,5000.0,4975.000000,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500.0,2500.0,2500.000000,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400.0,2400.0,2400.000000,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000.0,10000.0,10000.000000,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000.0,3000.0,3000.000000,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1075269,1311441,5000.0,5000.0,5000.000000,36 months,7.90,156.46,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1069639,1304742,7000.0,7000.0,7000.000000,60 months,15.96,170.08,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1072053,1288686,3000.0,3000.0,3000.000000,36 months,18.64,109.43,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1071795,1306957,5600.0,5600.0,5600.000000,60 months,21.28,152.39,F,F2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1071570,1306721,5375.0,5375.0,5350.000000,60 months,12.69,121.45,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1070078,1305201,6500.0,6500.0,6500.000000,60 months,14.65,153.45,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1069908,1305008,12000.0,12000.0,12000.000000,36 months,12.69,402.54,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1064687,1298717,9000.0,9000.0,9000.000000,36 months,13.49,305.38,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1069866,1304956,3000.0,3000.0,3000.000000,36 months,9.91,96.68,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1069057,1303503,10000.0,10000.0,10000.000000,36 months,10.65,325.74,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1069759,1304871,1000.0,1000.0,1000.000000,36 months,16.29,35.31,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1065775,1299699,10000.0,10000.0,10000.000000,36 months,15.27,347.98,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1069971,1304884,3600.0,3600.0,3600.000000,36 months,6.03,109.57,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1062474,1294539,6000.0,6000.0,6000.000000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1069742,1304855,9200.0,9200.0,9200.000000,36 months,6.03,280.01,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1069740,1284848,20250.0,20250.0,19142.161077,60 months,15.27,484.63,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1039153,1269083,21000.0,21000.0,21000.000000,36 months,12.42,701.73,B,B4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1069710,1304821,10000.0,10000.0,10000.000000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1069700,1304810,10000.0,10000.0,10000.000000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1069559,1304634,6000.0,6000.0,6000.000000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1069697,1273773,15000.0,15000.0,15000.000000,36 months,9.91,483.38,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1069800,1304679,15000.0,15000.0,8725.000000,36 months,14.27,514.64,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1069657,1304764,5000.0,5000.0,5000.000000,60 months,16.77,123.65,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1069799,1304678,4000.0,4000.0,4000.000000,36 months,11.71,132.31,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1047704,1278806,8500.0,8500.0,8500.000000,36 months,11.71,281.15,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887349,36691397,39434133,20000.0,20000.0,20000.000000,36 months,6.99,617.46,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,39700.0,NaN,NaN,NaN
887350,36500819,39232937,10300.0,10300.0,10300.000000,60 months,13.66,237.86,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,22000.0,NaN,NaN,NaN
887351,36743377,39486112,4200.0,4200.0,4200.000000,36 months,15.99,147.64,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,20400.0,NaN,NaN,NaN
887352,36231083,38942474,15000.0,15000.0,15000.000000,36 months,11.99,498.15,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,9700.0,NaN,NaN,NaN
887353,36371802,39103231,15000.0,15000.0,15000.000000,60 months,11.44,329.44,B,B4,...,NaN,NaN,NaN,NaN,NaN,NaN,26100.0,NaN,NaN,NaN
887354,36250801,38962184,6000.0,6000.0,6000.000000,36 months,17.86,216.50,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,8500.0,NaN,NaN,NaN
887355,36331554,39042967,26950.0,26950.0,26950.000000,36 months,8.19,846.88,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,129100.0,NaN,NaN,NaN
887356,36460697,39182359,23000.0,23000.0,23000.000000,60 months,15.59,554.32,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,65600.0,NaN,NaN,NaN
887357,35773415,38468842,18700.0,18700.0,18700.000000,60 months,17.86,473.44,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,10200.0,NaN,NaN,NaN
887358,36440728,39152101,25000.0,25000.0,25000.000000,60 months,15.99,607.82,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,18700.0,NaN,NaN,NaN
887359,35591131,38288343,25000.0,25000.0,25000.000000,60 months,15.59,602.52,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,24400.0,NaN,NaN,NaN
887360,36361815,39093260,26500.0,26500.0,26500.000000,60 months,8.67,545.87,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,118600.0,NaN,NaN,NaN
887361,36201871,38913321,21000.0,21000.0,21000.000000,36 months,6.03,639.15,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,76300.0,NaN,NaN,NaN
887362,36381756,39013193,8000.0,8000.0,8000.000000,36 months,8.19,251.40,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,7300.0,NaN,NaN,NaN
887363,36231724,38943173,12000.0,12000.0,12000.000000,36 months,9.49,384.34,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,11900.0,NaN,NaN,NaN
887364,36231718,38943165,10775.0,10775.0,10775.000000,36 months,6.03,327.95,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,41700.0,NaN,NaN,NaN
887365,36381704,39013139,7000.0,7000.0,7000.000000,36 months,14.31,240.30,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,9900.0,NaN,NaN,NaN
887366,36241316,38952731,6225.0,6225.0,6225.000000,36 months,16.49,220.37,D,D3,...,NaN,NaN,NaN,NaN,NaN,NaN,1800.0,NaN,NaN,NaN
887367,36301729,39023153,10000.0,10000.0,10000.000000,36 months,6.49,306.45,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,30300.0,NaN,NaN,NaN
887368,36250208,38961532,13150.0,13150.0,13150.000000,60 months,14.99,312.77,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,20700.0,NaN,NaN,NaN
887369,36421485,39142898,4000.0,4000.0,4000.000000,36 months,8.67,126.59,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,30100.0,NaN,NaN,NaN
887370,35094480,37777829,7500.0,7500.0,7500.000000,36 months,9.49,240.22,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,14500.0,NaN,NaN,NaN
887371,36260758,38972123,10850.0,10850.0,10850.000000,36 months,19.24,399.04,E,E2,...,NaN,NaN,NaN,NaN,NaN,NaN,16800.0,NaN,NaN,NaN
887372,36330911,39042282,12000.0,12000.0,12000.000000,36 months,11.99,398.52,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,30300.0,NaN,NaN,NaN
887373,36221446,38932858,11575.0,11575.0,11575.000000,36 months,15.59,404.61,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,28100.0,NaN,NaN,NaN
887374,36371250,39102635,10000.0,10000.0,10000.000000,36 months,11.99,332.10,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,17100.0,NaN,NaN,NaN
887375,36441262,39152692,24000.0,24000.0,24000.000000,36 months,11.99,797.03,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,10200.0,NaN,NaN,NaN
887376,36271333,38982739,13000.0,13000.0,13000.000000,60 months,15.99,316.07,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,NaN,NaN,NaN
887377,36490806,39222577,12000.0,12000.0,12000.000000,60 months,19.99,317.86,E,E3,...,NaN,NaN,NaN,NaN,NaN,NaN,27000.0,NaN,NaN,NaN
887378,36271262,38982659,20000.0,20000.0,20000.000000,36 months,11.99,664.20,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,41700.0,NaN,NaN,NaN

In [6]:
filter = ['loan_amnt', 'term', 'int_rate', 'grade', 
          'emp_length', 'home_ownership', 'annual_inc', 'loan_status', 'purpose',
          'payment_to_income_ratio', 'delinq_2yrs', 'earliest_cr_line', 
          'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 
          'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'application_type',
          'acc_now_delinq']

In [7]:
df_smaller = df.filter(items=filter)

In [8]:
df_smaller.head()

,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,loan_status,purpose,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,application_type,acc_now_delinq
0,5000.0,36 months,10.65,B,10+ years,RENT,24000.0,Fully Paid,credit_card,0.0,Jan-1985,1.0,NaN,NaN,3.0,0.0,13648.0,83.7,INDIVIDUAL,0.0
1,2500.0,60 months,15.27,C,< 1 year,RENT,30000.0,Charged Off,car,0.0,Apr-1999,5.0,NaN,NaN,3.0,0.0,1687.0,9.4,INDIVIDUAL,0.0
2,2400.0,36 months,15.96,C,10+ years,RENT,12252.0,Fully Paid,small_business,0.0,Nov-2001,2.0,NaN,NaN,2.0,0.0,2956.0,98.5,INDIVIDUAL,0.0
3,10000.0,36 months,13.49,C,10+ years,RENT,49200.0,Fully Paid,other,0.0,Feb-1996,1.0,35.0,NaN,10.0,0.0,5598.0,21.0,INDIVIDUAL,0.0
4,3000.0,60 months,12.69,B,1 year,RENT,80000.0,Current,other,0.0,Jan-1996,0.0,38.0,NaN,15.0,0.0,27783.0,53.9,INDIVIDUAL,0.0

In [9]:
df_smaller.info

<bound method DataFrame.info of         loan_amnt        term  int_rate grade emp_length home_ownership  \
0          5000.0   36 months     10.65     B  10+ years           RENT
1          2500.0   60 months     15.27     C   < 1 year           RENT
2          2400.0   36 months     15.96     C  10+ years           RENT
3         10000.0   36 months     13.49     C  10+ years           RENT
4          3000.0   60 months     12.69     B     1 year           RENT
5          5000.0   36 months      7.90     A    3 years           RENT
6          7000.0   60 months     15.96     C    8 years           RENT
7          3000.0   36 months     18.64     E    9 years           RENT
8          5600.0   60 months     21.28     F    4 years            OWN
9          5375.0   60 months     12.69     B   < 1 year           RENT
10         6500.0   60 months     14.65     C    5 years            OWN
11        12000.0   36 months     12.69     B  10+ years            OWN
12         9000.0   36 months     13.49     C   < 1 year           RENT
13         3000.0   36 months      9.91     B    3 years           RENT
14        10000.0   36 months     10.65     B    3 years           RENT
15         1000.0   36 months     16.29     D   < 1 year           RENT
16        10000.0   36 months     15.27     C    4 years           RENT
17         3600.0   36 months      6.03     A  10+ years       MORTGAGE
18         6000.0   36 months     11.71     B     1 year       MORTGAGE
19         9200.0   36 months      6.03     A    6 years           RENT
20        20250.0   60 months     15.27     C    3 years           RENT
21        21000.0   36 months     12.42     B  10+ years           RENT
22        10000.0   36 months     11.71     B  10+ years            OWN
23        10000.0   36 months     11.71     B    5 years           RENT
24         6000.0   36 months     11.71     B     1 year           RENT
25        15000.0   36 months      9.91     B    2 years       MORTGAGE
26        15000.0   36 months     14.27     C    9 years           RENT
27         5000.0   60 months     16.77     D    2 years           RENT
28         4000.0   36 months     11.71     B  10+ years       MORTGAGE
29         8500.0   36 months     11.71     B   < 1 year           RENT
...           ...         ...       ...   ...        ...            ...
887349    20000.0   36 months      6.99     A    2 years       MORTGAGE
887350    10300.0   60 months     13.66     C  10+ years           RENT
887351     4200.0   36 months     15.99     D  10+ years       MORTGAGE
887352    15000.0   36 months     11.99     B   < 1 year           RENT
887353    15000.0   60 months     11.44     B    4 years           RENT
887354     6000.0   36 months     17.86     D  10+ years       MORTGAGE
887355    26950.0   36 months      8.19     A        NaN           RENT
887356    23000.0   60 months     15.59     D  10+ years       MORTGAGE
887357    18700.0   60 months     17.86     D  10+ years           RENT
887358    25000.0   60 months     15.99     D    3 years           RENT
887359    25000.0   60 months     15.59     D        NaN            OWN
887360    26500.0   60 months      8.67     B  10+ years       MORTGAGE
887361    21000.0   36 months      6.03     A  10+ years       MORTGAGE
887362     8000.0   36 months      8.19     A    9 years       MORTGAGE
887363    12000.0   36 months      9.49     B    4 years           RENT
887364    10775.0   36 months      6.03     A   < 1 year           RENT
887365     7000.0   36 months     14.31     C  10+ years           RENT
887366     6225.0   36 months     16.49     D    2 years           RENT
887367    10000.0   36 months      6.49     A     1 year           RENT
887368    13150.0   60 months     14.99     C    8 years       MORTGAGE
887369     4000.0   36 months      8.67     B  10+ years       MORTGAGE
887370     7500.0   36 months      9.49     B    8 years           RENT
887371    10850.0   36 months     19.24     E        NaN            OWN
887372    12000.0   36 months     11.99     B   < 1 year       MORTGAGE
887373    11575.0   36 months     15.59     D  10+ years           RENT
887374    10000.0   36 months     11.99     B    8 years           RENT
887375    24000.0   36 months     11.99     B  10+ years       MORTGAGE
887376    13000.0   60 months     15.99     D    5 years           RENT
887377    12000.0   60 months     19.99     E     1 year           RENT
887378    20000.0   36 months     11.99     B  10+ years           RENT

        annual_inc  loan_status             purpose  delinq_2yrs  \
0         24000.00   Fully Paid         credit_card          0.0
1         30000.00  Charged Off                 car          0.0
2         12252.00   Fully Paid      small_business          0.0
3         49200.00   Fully Paid               other          0.0
4         80000.00      Current               other          0.0
5         36000.00   Fully Paid             wedding          0.0
6         47004.00      Current  debt_consolidation          0.0
7         48000.00   Fully Paid                 car          0.0
8         40000.00  Charged Off      small_business          0.0
9         15000.00  Charged Off               other          0.0
10        72000.00   Fully Paid  debt_consolidation          0.0
11        75000.00   Fully Paid  debt_consolidation          0.0
12        30000.00  Charged Off  debt_consolidation          0.0
13        15000.00   Fully Paid         credit_card          0.0
14       100000.00  Charged Off               other          0.0
15        28000.00   Fully Paid  debt_consolidation          0.0
16        42000.00   Fully Paid    home_improvement          0.0
17       110000.00   Fully Paid      major_purchase          0.0
18        84000.00   Fully Paid             medical          2.0
19        77385.19   Fully Paid  debt_consolidation          0.0
20        43370.00   Fully Paid  debt_consolidation          0.0
21       105000.00  Charged Off  debt_consolidation          0.0
22        50000.00   Fully Paid         credit_card          0.0
23        50000.00   Fully Paid  debt_consolidation          0.0
24        76000.00  Charged Off      major_purchase          0.0
25        92000.00   Fully Paid         credit_card          0.0
26        60000.00  Charged Off  debt_consolidation          0.0
27        50004.00  Charged Off               other          3.0
28       106000.00   Fully Paid  debt_consolidation          1.0
29        25000.00   Fully Paid         credit_card          0.0
...            ...          ...                 ...          ...
887349    72000.00      Current  debt_consolidation          0.0
887350    93600.00      Current  debt_consolidation          1.0
887351    48000.00  Charged Off             medical          0.0
887352    70000.00      Current  debt_consolidation          0.0
887353    57000.00      Current  debt_consolidation          0.0
887354    90000.00      Current  debt_consolidation          0.0
887355    54000.00      Current  debt_consolidation          0.0
887356    50000.00      Current         credit_card          0.0
887357    52000.00      Current  debt_consolidation          0.0
887358   103000.00      Current  debt_consolidation          0.0
887359    55000.00      Current  debt_consolidation          0.0
887360    92000.00      Current  debt_consolidation          1.0
887361    65000.00      Current         credit_card          0.0
887362    50000.00      Current  debt_consolidation          0.0
887363    40000.00      Current  debt_consolidation          1.0
887364    54000.00   Fully Paid  debt_consolidation          1.0
887365    57000.00      Current  debt_consolidation          2.0
887366    27000.00   Fully Paid  debt_consolidation          0.0
887367    75000.00      Current  debt_consolidation          0.0
887368    30000.00      Current      major_purchase          0.0
887369    50000.00   Fully Paid                 car          0.0
887370    40000.00      Current  debt_consolidation          0.0
887371    32000.00  Charged Off  debt_consolidation          0.0
887372    63000.00      Current         credit_card          1.0
887373    25400.00      Current         credit_card          0.0
887374    31000.00      Current  debt_consolidation          0.0
887375    79000.00      Current    home_improvement          0.0
887376    35000.00      Current  debt_consolidation          0.0
887377    64400.00      Current  debt_consolidation          1.0
887378   100000.00      Current         credit_card          0.0

       earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
0              Jan-1985             1.0                     NaN
1              Apr-1999             5.0                     NaN
2              Nov-2001             2.0                     NaN
3              Feb-1996             1.0                    35.0
4              Jan-1996             0.0                    38.0
5              Nov-2004             3.0                     NaN
6              Jul-2005             1.0                     NaN
7              Jan-2007             2.0                     NaN
8              Apr-2004             2.0                     NaN
9              Sep-2004             0.0                     NaN
10             Jan-1998             2.0                     NaN
11             Oct-1989             0.0                     NaN
12             Apr-2004             1.0                     NaN
13             Jul-2003             2.0                     NaN
14             May-1991             2.0                     NaN
15             Sep-2007             1.0                     NaN
16             Oct-1998             2.0                    61.0
17             Aug-1993             0.0                     NaN
18             Oct-2003             0.0                     8.0
19             Jan-2001             0.0                     NaN
20             Nov-1997             3.0                     NaN
21             Feb-1983             0.0                     NaN
22             Jul-1985             0.0                     NaN
23             Apr-2003             0.0                     NaN
24             Jun-2001             1.0                     NaN
25             Feb-2002             0.0                     NaN
26             Oct-2003             1.0                     NaN
27             Oct-2003             0.0                    20.0
28             Aug-1984             0.0                    18.0
29             Nov-2006             0.0                     NaN
...                 ...             ...                     ...
887349         Mar-1998             1.0                    69.0
887350         Aug-2002             0.0                    17.0
887351         Aug-1990             0.0                    38.0
887352         Dec-2006             0.0                     NaN
887353         Jan-1989             0.0                     NaN
887354         Jun-2001             0.0                     NaN
887355         Jun-1993             0.0                     NaN
887356         Dec-1994             0.0                     NaN
887357         Jul-2002             0.0                    30.0
887358         May-2003             0.0                     NaN
887359         May-2003             0.0                     NaN
887360         Aug-1983             0.0                    17.0
887361         Oct-1994             0.0                     NaN
887362         Sep-2003             1.0                    24.0
887363         Oct-2006             0.0                     8.0
887364         Nov-1975             0.0                    16.0
887365         Nov-2006             3.0                    10.0
887366         Feb-2011             1.0                     NaN
887367         Mar-2000             0.0                    29.0
887368         May-1994             0.0                     NaN
887369         Sep-2002             0.0                     NaN
887370         Aug-1994             0.0                    69.0
887371         Jun-2002             1.0                    65.0
887372         Jun-1995             0.0                     9.0
887373         Jul-1999             0.0                     NaN
887374         Sep-2004             0.0                     NaN
887375         Mar-1974             1.0                    26.0
887376         Sep-2003             0.0                     NaN
887377         Oct-2003             2.0                    22.0
887378         Dec-2001             1.0                     NaN

        mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
0                          NaN       3.0      0.0    13648.0       83.70
1                          NaN       3.0      0.0     1687.0        9.40
2                          NaN       2.0      0.0     2956.0       98.50
3                          NaN      10.0      0.0     5598.0       21.00
4                          NaN      15.0      0.0    27783.0       53.90
5                          NaN       9.0      0.0     7963.0       28.30
6                          NaN       7.0      0.0    17726.0       85.60
7                          NaN       4.0      0.0     8221.0       87.50
8                          NaN      11.0      0.0     5210.0       32.60
9                          NaN       2.0      0.0     9279.0       36.50
10                         NaN      14.0      0.0     4032.0       20.60
11                         NaN      12.0      0.0    23336.0       67.10
12                         NaN       4.0      0.0    10452.0       91.70
13                         NaN      11.0      0.0     7323.0       43.10
14                         NaN      14.0      0.0    11997.0       55.50
15                         NaN      11.0      0.0     6524.0       81.50
16                         NaN      14.0      0.0    24043.0       70.20
17                         NaN      20.0      0.0    22836.0       16.00
18                         NaN       4.0      0.0        0.0       37.73
19                         NaN       8.0      0.0     7314.0       23.10
20                         NaN       8.0      0.0    17813.0       85.60
21                         NaN       7.0      0.0    32135.0       90.30
22                         NaN       8.0      0.0    10056.0       82.40
23                         NaN       6.0      0.0    17800.0       91.80
24                         NaN       7.0      0.0     5963.0       29.70
25                         NaN       8.0      0.0    13707.0       93.90
26                         NaN       7.0      0.0     5872.0       57.60
27                         NaN      14.0      0.0     4345.0       59.50
28                         NaN      12.0      0.0     6110.0       37.70
29                         NaN       8.0      0.0     6441.0       59.10
...                        ...       ...      ...        ...         ...
887349                     NaN      15.0      0.0    21100.0       53.10
887350                     NaN      13.0      0.0    10260.0       46.60
887351                     NaN      13.0      0.0    12943.0       63.40
887352                     NaN       8.0      0.0     9508.0       98.00
887353                     NaN       8.0      0.0    14848.0       56.90
887354                     NaN       9.0      0.0     6707.0       78.90
887355                     NaN      14.0      0.0    32167.0       24.90
887356                     NaN      13.0      0.0    41546.0       63.30
887357                     NaN       8.0      0.0     7710.0       75.60
887358                     NaN       5.0      0.0    17275.0       92.40
887359                     NaN       9.0      0.0    13860.0       56.80
887360                     NaN      10.0      0.0    75645.0       65.10
887361                     NaN      11.0      0.0    23356.0       30.60
887362                     NaN      11.0      0.0     4611.0       63.20
887363                     NaN       8.0      0.0     8731.0       73.40
887364                     NaN       9.0      0.0    10776.0       25.80
887365                    52.0      13.0      2.0     2684.0       27.10
887366                     NaN       3.0      0.0     1756.0       97.60
887367                     NaN       9.0      0.0    10529.0       34.70
887368                     NaN       3.0      0.0      672.0        3.20
887369                    84.0      11.0      1.0     1700.0        5.60
887370                    88.0      10.0      1.0     6361.0       43.90
887371                     NaN       9.0      0.0     6987.0       41.60
887372                     NaN      13.0      0.0    21110.0       69.70
887373                     NaN       9.0      0.0    18266.0       65.00
887374                    77.0       9.0      1.0    14037.0       82.10
887375                     NaN       5.0      0.0     8621.0       84.50
887376                    84.0       9.0      1.0    11031.0       61.30
887377                     NaN      17.0      0.0     8254.0       30.60
887378                   110.0       8.0      1.0    33266.0       79.80

       application_type  acc_now_delinq
0            INDIVIDUAL             0.0
1            INDIVIDUAL             0.0
2            INDIVIDUAL             0.0
3            INDIVIDUAL             0.0
4            INDIVIDUAL             0.0
5            INDIVIDUAL             0.0
6            INDIVIDUAL             0.0
7            INDIVIDUAL             0.0
8            INDIVIDUAL             0.0
9            INDIVIDUAL             0.0
10           INDIVIDUAL             0.0
11           INDIVIDUAL             0.0
12           INDIVIDUAL             0.0
13           INDIVIDUAL             0.0
14           INDIVIDUAL             0.0
15           INDIVIDUAL             0.0
16           INDIVIDUAL             0.0
17           INDIVIDUAL             0.0
18           INDIVIDUAL             0.0
19           INDIVIDUAL             0.0
20           INDIVIDUAL             0.0
21           INDIVIDUAL             0.0
22           INDIVIDUAL             0.0
23           INDIVIDUAL             0.0
24           INDIVIDUAL             0.0
25           INDIVIDUAL             0.0
26           INDIVIDUAL             0.0
27           INDIVIDUAL             0.0
28           INDIVIDUAL             0.0
29           INDIVIDUAL             0.0
...                 ...             ...
887349       INDIVIDUAL             0.0
887350       INDIVIDUAL             0.0
887351       INDIVIDUAL             0.0
887352       INDIVIDUAL             0.0
887353       INDIVIDUAL             0.0
887354       INDIVIDUAL             0.0
887355       INDIVIDUAL             0.0
887356       INDIVIDUAL             0.0
887357       INDIVIDUAL             0.0
887358       INDIVIDUAL             0.0
887359       INDIVIDUAL             0.0
887360       INDIVIDUAL             0.0
887361       INDIVIDUAL             0.0
887362       INDIVIDUAL             0.0
887363       INDIVIDUAL             0.0
887364       INDIVIDUAL             0.0
887365       INDIVIDUAL             0.0
887366       INDIVIDUAL             0.0
887367       INDIVIDUAL             0.0
887368       INDIVIDUAL             0.0
887369       INDIVIDUAL             0.0
887370       INDIVIDUAL             0.0
887371       INDIVIDUAL             0.0
887372       INDIVIDUAL             0.0
887373       INDIVIDUAL             0.0
887374       INDIVIDUAL             0.0
887375       INDIVIDUAL             0.0
887376       INDIVIDUAL             0.0
887377       INDIVIDUAL             0.0
887378       INDIVIDUAL             0.0

[887379 rows x 20 columns]>

In [10]:
df_clean = df_smaller.copy()

In [11]:
excluded = ['Issued',
                'Does not meet the credit policy. Status:Charged Off',
                'Does not meet the credit policy. Status:Fully Paid',
               ]
good = ['Current', 'Fully Paid']
bad = ['Charged Off', 'Default', 'In Grace Period', 'Late (16-30 days)', 'Late (31-120 days)']

In [12]:
def get_status (status):
    """
    Assign loans to either good or bad loans based on their status
    """
    try: 
        status=status.strip()
        if status in good:
            return "good"
        elif status in bad:
            return "bad"
        else: 
            return "excluded"
    except: 
        return "excluded"

In [13]:
df_clean['loan_status']=df_clean['loan_status'].apply(lambda x: get_status(x))

In [14]:
df_clean = df_clean[df_clean['loan_status']!='excluded']

In [15]:
df_clean.groupby('loan_status').count()

,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,purpose,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,application_type,acc_now_delinq
loan_status,,,,,,,,,,,,,,,,,,,
bad,66668,66668,66668,66668,62973,66668,66668,66668,66668,66668,66668,31695,9260,66668,66668,66668,66607,66668,66668
good,809502,809502,809502,809502,769037,809502,809502,809502,809502,809502,809502,395378,125337,809502,809502,809502,809104,809502,809502

In [16]:
# Check null values for rest of records

df_clean.isnull().sum()

loan_amnt                      0
term                           0
int_rate                       0
grade                          0
emp_length                 44160
home_ownership                 0
annual_inc                     0
loan_status                    0
purpose                        0
delinq_2yrs                    0
earliest_cr_line               0
inq_last_6mths                 0
mths_since_last_delinq    449097
mths_since_last_record    741573
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                   459
application_type               0
acc_now_delinq                 0
dtype: int64

In [17]:
# Fill the null value for 'mths_since_last_delinq' with zero as zero is default case for majority of loans

df_clean['mths_since_last_delinq'].fillna(value=0, inplace=True)

In [18]:
# Fill the null value for 'mths_since_last_record' with zero as zero is default case for majority ofloans

df_clean['mths_since_last_record'].fillna(value=0, inplace=True)

In [19]:
# Fill the null value for 'mths_since_last_record' as zero is majority of case

df_clean['revol_util'].fillna(
    value=df_clean['revol_util'].mean(), inplace=True)

In [20]:
def get_employee_length(length):
    """
    This is to extract numerical value of emp_length
    For simplicity, approximation was used.
    <1 years will be treated as 1 year
    >10 years will be treated as 10 years
    """
    try:
        length = length.strip()
        year = re.findall(r'(\d+)', length)
        return int(year[0]) 
    except:
        return None

In [21]:
df_clean['emp_length'] = df_clean['emp_length'].apply(lambda x: get_employee_length(x))

In [22]:
df_clean['emp_length'].fillna(
    value=df_clean['emp_length'].mean(), inplace=True)

In [23]:
# All Null values have been appropriately handled

df_clean.isnull().sum()

loan_amnt                 0
term                      0
int_rate                  0
grade                     0
emp_length                0
home_ownership            0
annual_inc                0
loan_status               0
purpose                   0
delinq_2yrs               0
earliest_cr_line          0
inq_last_6mths            0
mths_since_last_delinq    0
mths_since_last_record    0
open_acc                  0
pub_rec                   0
revol_bal                 0
revol_util                0
application_type          0
acc_now_delinq            0
dtype: int64

In [24]:
# Break down terms of loan into 2 categories

df_clean=pd.get_dummies(df_clean, prefix=['term'],columns=['term'])

In [25]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'grade', 'emp_length', 'home_ownership',
       'annual_inc', 'loan_status', 'purpose', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'application_type', 'acc_now_delinq', 'term_ 36 months',
       'term_ 60 months'],
      dtype='object')

In [26]:
# Break down grades into categories

df_clean=pd.get_dummies(df_clean, prefix=['grade'],columns=['grade'])

In [27]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'emp_length', 'home_ownership', 'annual_inc',
       'loan_status', 'purpose', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'application_type',
       'acc_now_delinq', 'term_ 36 months', 'term_ 60 months', 'grade_A',
       'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G'],
      dtype='object')

In [28]:
def get_home_ownership(ownership):
    """
    Break doen home_ownership into 4 categories:

    """
    ownership=str(ownership).strip()
    rent=['RENT']
    own=['OWN']
    mortgage=[ 'MORTGAGE']
    
    if ownership in rent:
        return 'rent'
    elif ownership in mortgage:
        return 'mortgage'
    elif ownership in own: 
        return 'own'
    else: 
        return 'others'

In [29]:
df_clean['home_ownership']=df_clean['home_ownership'].apply(lambda x: get_home_ownership(x))

In [30]:
df_clean.groupby('home_ownership').count()

,loan_amnt,int_rate,emp_length,annual_inc,loan_status,purpose,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,...,acc_now_delinq,term_ 36 months,term_ 60 months,grade_A,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G
home_ownership,,,,,,,,,,,,,,,,,,,,,
mortgage,438081,438081,438081,438081,438081,438081,438081,438081,438081,438081,...,438081,438081,438081,438081,438081,438081,438081,438081,438081,438081
others,192,192,192,192,192,192,192,192,192,192,...,192,192,192,192,192,192,192,192,192,192
own,86245,86245,86245,86245,86245,86245,86245,86245,86245,86245,...,86245,86245,86245,86245,86245,86245,86245,86245,86245,86245
rent,351652,351652,351652,351652,351652,351652,351652,351652,351652,351652,...,351652,351652,351652,351652,351652,351652,351652,351652,351652,351652

In [31]:
df_clean = pd.get_dummies(df_clean, prefix=['home_ownership'], columns=['home_ownership'])

In [32]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'emp_length', 'annual_inc', 'loan_status',
       'purpose', 'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'application_type',
       'acc_now_delinq', 'term_ 36 months', 'term_ 60 months', 'grade_A',
       'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G',
       'home_ownership_mortgage', 'home_ownership_others',
       'home_ownership_own', 'home_ownership_rent'],
      dtype='object')

In [33]:
df_clean=pd.get_dummies(df_clean, prefix=['purpose'], columns=['purpose'])

In [34]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'emp_length', 'annual_inc', 'loan_status',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'application_type',
       'acc_now_delinq', 'term_ 36 months', 'term_ 60 months', 'grade_A',
       'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G',
       'home_ownership_mortgage', 'home_ownership_others',
       'home_ownership_own', 'home_ownership_rent', 'purpose_car',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement', 'purpose_house',
       'purpose_major_purchase', 'purpose_medical', 'purpose_moving',
       'purpose_other', 'purpose_renewable_energy', 'purpose_small_business',
       'purpose_vacation', 'purpose_wedding'],
      dtype='object')

In [35]:
def get_earliest_cr_line(string):
    """
    This is to calculate years of credit history.
    Since the data is from 2016, use 2016 minus the 
    starting year to estimate years of credit history
    
    """
    string = string.strip()
    year = re.findall(r'(\d+)', string)
    return (2016-int(year[0]))

In [36]:
df_clean['earliest_cr_line'] = df_clean['earliest_cr_line'].apply(lambda x: get_earliest_cr_line(x))

In [37]:
def inverse(value):
    try:
        return 1/value
    except: 
        return 0

In [38]:
# Take inverse of months since last delinquishing date as this is is inversed related to default prediction

df_clean['inversed_mths_since_last_delinq']=df_clean['mths_since_last_delinq'].apply(lambda x: inverse(x))

In [39]:
# Take inverse of months since last record as this is is inversed related to default to default prediction

df_clean['inversed_mths_since_last_record']=df_clean['mths_since_last_record'].apply(lambda x: inverse(x))

In [40]:
df_clean.drop(['mths_since_last_delinq', 'mths_since_last_record'], axis=1)

,loan_amnt,int_rate,emp_length,annual_inc,loan_status,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,...,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,inversed_mths_since_last_delinq,inversed_mths_since_last_record
0,5000.0,10.65,10.000000,24000.00,good,0.0,31,1.0,3.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
1,2500.0,15.27,1.000000,30000.00,bad,0.0,17,5.0,3.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
2,2400.0,15.96,10.000000,12252.00,good,0.0,15,2.0,2.0,0.0,...,0,0,0,0,0,1,0,0,0.000000,0.000000
3,10000.0,13.49,10.000000,49200.00,good,0.0,20,1.0,10.0,0.0,...,0,0,0,1,0,0,0,0,0.028571,0.000000
4,3000.0,12.69,1.000000,80000.00,good,0.0,20,0.0,15.0,0.0,...,0,0,0,1,0,0,0,0,0.026316,0.000000
5,5000.0,7.90,3.000000,36000.00,good,0.0,12,3.0,9.0,0.0,...,0,0,0,0,0,0,0,1,0.000000,0.000000
6,7000.0,15.96,8.000000,47004.00,good,0.0,11,1.0,7.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
7,3000.0,18.64,9.000000,48000.00,good,0.0,9,2.0,4.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
8,5600.0,21.28,4.000000,40000.00,bad,0.0,12,2.0,11.0,0.0,...,0,0,0,0,0,1,0,0,0.000000,0.000000
9,5375.0,12.69,1.000000,15000.00,bad,0.0,12,0.0,2.0,0.0,...,0,0,0,1,0,0,0,0,0.000000,0.000000
10,6500.0,14.65,5.000000,72000.00,good,0.0,18,2.0,14.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
11,12000.0,12.69,10.000000,75000.00,good,0.0,27,0.0,12.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
12,9000.0,13.49,1.000000,30000.00,bad,0.0,12,1.0,4.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
13,3000.0,9.91,3.000000,15000.00,good,0.0,13,2.0,11.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
14,10000.0,10.65,3.000000,100000.00,bad,0.0,25,2.0,14.0,0.0,...,0,0,0,1,0,0,0,0,0.000000,0.000000
15,1000.0,16.29,1.000000,28000.00,good,0.0,9,1.0,11.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
16,10000.0,15.27,4.000000,42000.00,good,0.0,18,2.0,14.0,0.0,...,0,0,0,0,0,0,0,0,0.016393,0.000000
17,3600.0,6.03,10.000000,110000.00,good,0.0,23,0.0,20.0,0.0,...,1,0,0,0,0,0,0,0,0.000000,0.000000
18,6000.0,11.71,1.000000,84000.00,good,2.0,13,0.0,4.0,0.0,...,0,1,0,0,0,0,0,0,0.125000,0.000000
19,9200.0,6.03,6.000000,77385.19,good,0.0,15,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
20,20250.0,15.27,3.000000,43370.00,good,0.0,19,3.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
21,21000.0,12.42,10.000000,105000.00,bad,0.0,33,0.0,7.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
22,10000.0,11.71,10.000000,50000.00,good,0.0,31,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
23,10000.0,11.71,5.000000,50000.00,good,0.0,13,0.0,6.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
24,6000.0,11.71,1.000000,76000.00,bad,0.0,15,1.0,7.0,0.0,...,1,0,0,0,0,0,0,0,0.000000,0.000000
25,15000.0,9.91,2.000000,92000.00,good,0.0,14,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
26,15000.0,14.27,9.000000,60000.00,bad,0.0,13,1.0,7.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
27,5000.0,16.77,2.000000,50004.00,bad,3.0,13,0.0,14.0,0.0,...,0,0,0,1,0,0,0,0,0.050000,0.000000
28,4000.0,11.71,10.000000,106000.00,good,1.0,32,0.0,12.0,0.0,...,0,0,0,0,0,0,0,0,0.055556,0.000000
29,8500.0,11.71,1.000000,25000.00,good,0.0,10,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887349,20000.0,6.99,2.000000,72000.00,good,0.0,18,1.0,15.0,0.0,...,0,0,0,0,0,0,0,0,0.014493,0.000000
887350,10300.0,13.66,10.000000,93600.00,good,1.0,14,0.0,13.0,0.0,...,0,0,0,0,0,0,0,0,0.058824,0.000000
887351,4200.0,15.99,10.000000,48000.00,bad,0.0,26,0.0,13.0,0.0,...,0,1,0,0,0,0,0,0,0.026316,0.000000
887352,15000.0,11.99,1.000000,70000.00,good,0.0,10,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887353,15000.0,11.44,4.000000,57000.00,good,0.0,27,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887354,6000.0,17.86,10.000000,90000.00,good,0.0,15,0.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887355,26950.0,8.19,6.098617,54000.00,good,0.0,23,0.0,14.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887356,23000.0,15.59,10.000000,50000.00,good,0.0,22,0.0,13.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887357,18700.0,17.86,10.000000,52000.00,good,0.0,14,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.033333,0.000000
887358,25000.0,15.99,3.000000,103000.00,good,0.0,13,0.0,5.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887359,25000.0,15.59,6.098617,55000.00,good,0.0,13,0.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887360,26500.0,8.67,10.000000,92000.00,good,1.0,33,0.0,10.0,0.0,...,0,0,0,0,0,0,0,0,0.058824,0.000000
887361,21000.0,6.03,10.000000,65000.00,good,0.0,22,0.0,11.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887362,8000.0,8.19,9.000000,50000.00,good,0.0,13,1.0,11.0,0.0,...,0,0,0,0,0,0,0,0,0.041667,0.000000
887363,12000.0,9.49,4.000000,40000.00,good,1.0,10,0.0,8.0,0.0,...,0,0,0,0,0,0,0,0,0.125000,0.000000
887364,10775.0,6.03,1.000000,54000.00,good,1.0,41,0.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.062500,0.000000
887365,7000.0,14.31,10.000000,57000.00,good,2.0,10,3.0,13.0,2.0,...,0,0,0,0,0,0,0,0,0.100000,0.019231
887366,6225.0,16.49,2.000000,27000.00,good,0.0,5,1.0,3.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887367,10000.0,6.49,1.000000,75000.00,good,0.0,16,0.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.034483,0.000000
887368,13150.0,14.99,8.000000,30000.00,good,0.0,22,0.0,3.0,0.0,...,1,0,0,0,0,0,0,0,0.000000,0.000000
887369,4000.0,8.67,10.000000,50000.00,good,0.0,14,0.0,11.0,1.0,...,0,0,0,0,0,0,0,0,0.000000,0.011905
887370,7500.0,9.49,8.000000,40000.00,good,0.0,22,0.0,10.0,1.0,...,0,0,0,0,0,0,0,0,0.014493,0.011364
887371,10850.0,19.24,6.098617,32000.00,bad,0.0,14,1.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.015385,0.000000
887372,12000.0,11.99,1.000000,63000.00,good,1.0,21,0.0,13.0,0.0,...,0,0,0,0,0,0,0,0,0.111111,0.000000
887373,11575.0,15.59,10.000000,25400.00,good,0.0,17,0.0,9.0,0.0,...,0,0,0,0,0,0,0,0,0.000000,0.000000
887374,10000.0,11.99,8.000000,31000.00,good,0.0,12,0.0,9.0,1.0,...,0,0,0,0,0,0,0,0,0.000000,0.012987
887375,24000.0,11.99,10.000000,79000.00,good,0.0,42,1.0,5.0,0.0,...,0,0,0,0,0,0,0,0,0.038462,0.000000
887376,13000.0,15.99,5.000000,35000.00,good,0.0,13,0.0,9.0,1.0,...,0,0,0,0,0,0,0,0,0.000000,0.011905
887377,12000.0,19.99,1.000000,64400.00,good,1.0,13,2.0,17.0,0.0,...,0,0,0,0,0,0,0,0,0.045455,0.000000
887378,20000.0,11.99,10.000000,100000.00,good,0.0,15,1.0,8.0,1.0,...,0,0,0,0,0,0,0,0,0.000000,0.009091

In [41]:
df_clean['income_to_debt_ratio']=df_clean['annual_inc']/df_clean['revol_bal']

In [42]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'emp_length', 'annual_inc', 'loan_status',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'application_type',
       'acc_now_delinq', 'term_ 36 months', 'term_ 60 months', 'grade_A',
       'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G',
       'home_ownership_mortgage', 'home_ownership_others',
       'home_ownership_own', 'home_ownership_rent', 'purpose_car',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement', 'purpose_house',
       'purpose_major_purchase', 'purpose_medical', 'purpose_moving',
       'purpose_other', 'purpose_renewable_energy', 'purpose_small_business',
       'purpose_vacation', 'purpose_wedding',
       'inversed_mths_since_last_delinq', 'inversed_mths_since_last_record',
       'income_to_debt_ratio'],
      dtype='object')

In [43]:
pd.get_dummies(df_clean, prefix=['application_type'], columns=['application_type'])

,loan_amnt,int_rate,emp_length,annual_inc,loan_status,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,...,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,inversed_mths_since_last_delinq,inversed_mths_since_last_record,income_to_debt_ratio,application_type_INDIVIDUAL,application_type_JOINT
0,5000.0,10.65,10.000000,24000.00,good,0.0,31,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,1.758499,1,0
1,2500.0,15.27,1.000000,30000.00,bad,0.0,17,5.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,17.783047,1,0
2,2400.0,15.96,10.000000,12252.00,good,0.0,15,2.0,0.0,0.0,...,0,0,1,0,0,0.000000,0.000000,4.144790,1,0
3,10000.0,13.49,10.000000,49200.00,good,0.0,20,1.0,35.0,0.0,...,1,0,0,0,0,0.028571,0.000000,8.788853,1,0
4,3000.0,12.69,1.000000,80000.00,good,0.0,20,0.0,38.0,0.0,...,1,0,0,0,0,0.026316,0.000000,2.879459,1,0
5,5000.0,7.90,3.000000,36000.00,good,0.0,12,3.0,0.0,0.0,...,0,0,0,0,1,0.000000,0.000000,4.520909,1,0
6,7000.0,15.96,8.000000,47004.00,good,0.0,11,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.651698,1,0
7,3000.0,18.64,9.000000,48000.00,good,0.0,9,2.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,5.838706,1,0
8,5600.0,21.28,4.000000,40000.00,bad,0.0,12,2.0,0.0,0.0,...,0,0,1,0,0,0.000000,0.000000,7.677543,1,0
9,5375.0,12.69,1.000000,15000.00,bad,0.0,12,0.0,0.0,0.0,...,1,0,0,0,0,0.000000,0.000000,1.616554,1,0
10,6500.0,14.65,5.000000,72000.00,good,0.0,18,2.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,17.857143,1,0
11,12000.0,12.69,10.000000,75000.00,good,0.0,27,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.213918,1,0
12,9000.0,13.49,1.000000,30000.00,bad,0.0,12,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.870264,1,0
13,3000.0,9.91,3.000000,15000.00,good,0.0,13,2.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.048341,1,0
14,10000.0,10.65,3.000000,100000.00,bad,0.0,25,2.0,0.0,0.0,...,1,0,0,0,0,0.000000,0.000000,8.335417,1,0
15,1000.0,16.29,1.000000,28000.00,good,0.0,9,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,4.291845,1,0
16,10000.0,15.27,4.000000,42000.00,good,0.0,18,2.0,61.0,0.0,...,0,0,0,0,0,0.016393,0.000000,1.746870,1,0
17,3600.0,6.03,10.000000,110000.00,good,0.0,23,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,4.816956,1,0
18,6000.0,11.71,1.000000,84000.00,good,2.0,13,0.0,8.0,0.0,...,0,0,0,0,0,0.125000,0.000000,inf,1,0
19,9200.0,6.03,6.000000,77385.19,good,0.0,15,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,10.580420,1,0
20,20250.0,15.27,3.000000,43370.00,good,0.0,19,3.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.434739,1,0
21,21000.0,12.42,10.000000,105000.00,bad,0.0,33,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.267465,1,0
22,10000.0,11.71,10.000000,50000.00,good,0.0,31,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,4.972156,1,0
23,10000.0,11.71,5.000000,50000.00,good,0.0,13,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.808989,1,0
24,6000.0,11.71,1.000000,76000.00,bad,0.0,15,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,12.745262,1,0
25,15000.0,9.91,2.000000,92000.00,good,0.0,14,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,6.711899,1,0
26,15000.0,14.27,9.000000,60000.00,bad,0.0,13,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,10.217984,1,0
27,5000.0,16.77,2.000000,50004.00,bad,3.0,13,0.0,20.0,0.0,...,1,0,0,0,0,0.050000,0.000000,11.508400,1,0
28,4000.0,11.71,10.000000,106000.00,good,1.0,32,0.0,18.0,0.0,...,0,0,0,0,0,0.055556,0.000000,17.348609,1,0
29,8500.0,11.71,1.000000,25000.00,good,0.0,10,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.881385,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887349,20000.0,6.99,2.000000,72000.00,good,0.0,18,1.0,69.0,0.0,...,0,0,0,0,0,0.014493,0.000000,3.412322,1,0
887350,10300.0,13.66,10.000000,93600.00,good,1.0,14,0.0,17.0,0.0,...,0,0,0,0,0,0.058824,0.000000,9.122807,1,0
887351,4200.0,15.99,10.000000,48000.00,bad,0.0,26,0.0,38.0,0.0,...,0,0,0,0,0,0.026316,0.000000,3.708568,1,0
887352,15000.0,11.99,1.000000,70000.00,good,0.0,10,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,7.362221,1,0
887353,15000.0,11.44,4.000000,57000.00,good,0.0,27,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.838901,1,0
887354,6000.0,17.86,10.000000,90000.00,good,0.0,15,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,13.418816,1,0
887355,26950.0,8.19,6.098617,54000.00,good,0.0,23,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,1.678739,1,0
887356,23000.0,15.59,10.000000,50000.00,good,0.0,22,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,1.203485,1,0
887357,18700.0,17.86,10.000000,52000.00,good,0.0,14,0.0,30.0,0.0,...,0,0,0,0,0,0.033333,0.000000,6.744488,1,0
887358,25000.0,15.99,3.000000,103000.00,good,0.0,13,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,5.962373,1,0
887359,25000.0,15.59,6.098617,55000.00,good,0.0,13,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.968254,1,0
887360,26500.0,8.67,10.000000,92000.00,good,1.0,33,0.0,17.0,0.0,...,0,0,0,0,0,0.058824,0.000000,1.216207,1,0
887361,21000.0,6.03,10.000000,65000.00,good,0.0,22,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,2.783011,1,0
887362,8000.0,8.19,9.000000,50000.00,good,0.0,13,1.0,24.0,0.0,...,0,0,0,0,0,0.041667,0.000000,10.843635,1,0
887363,12000.0,9.49,4.000000,40000.00,good,1.0,10,0.0,8.0,0.0,...,0,0,0,0,0,0.125000,0.000000,4.581377,1,0
887364,10775.0,6.03,1.000000,54000.00,good,1.0,41,0.0,16.0,0.0,...,0,0,0,0,0,0.062500,0.000000,5.011136,1,0
887365,7000.0,14.31,10.000000,57000.00,good,2.0,10,3.0,10.0,52.0,...,0,0,0,0,0,0.100000,0.019231,21.236960,1,0
887366,6225.0,16.49,2.000000,27000.00,good,0.0,5,1.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,15.375854,1,0
887367,10000.0,6.49,1.000000,75000.00,good,0.0,16,0.0,29.0,0.0,...,0,0,0,0,0,0.034483,0.000000,7.123184,1,0
887368,13150.0,14.99,8.000000,30000.00,good,0.0,22,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,44.642857,1,0
887369,4000.0,8.67,10.000000,50000.00,good,0.0,14,0.0,0.0,84.0,...,0,0,0,0,0,0.000000,0.011905,29.411765,1,0
887370,7500.0,9.49,8.000000,40000.00,good,0.0,22,0.0,69.0,88.0,...,0,0,0,0,0,0.014493,0.011364,6.288319,1,0
887371,10850.0,19.24,6.098617,32000.00,bad,0.0,14,1.0,65.0,0.0,...,0,0,0,0,0,0.015385,0.000000,4.579934,1,0
887372,12000.0,11.99,1.000000,63000.00,good,1.0,21,0.0,9.0,0.0,...,0,0,0,0,0,0.111111,0.000000,2.984368,1,0
887373,11575.0,15.59,10.000000,25400.00,good,0.0,17,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,1.390562,1,0
887374,10000.0,11.99,8.000000,31000.00,good,0.0,12,0.0,0.0,77.0,...,0,0,0,0,0,0.000000,0.012987,2.208449,1,0
887375,24000.0,11.99,10.000000,79000.00,good,0.0,42,1.0,26.0,0.0,...,0,0,0,0,0,0.038462,0.000000,9.163670,1,0
887376,13000.0,15.99,5.000000,35000.00,good,0.0,13,0.0,0.0,84.0,...,0,0,0,0,0,0.000000,0.011905,3.172876,1,0
887377,12000.0,19.99,1.000000,64400.00,good,1.0,13,2.0,22.0,0.0,...,0,0,0,0,0,0.045455,0.000000,7.802278,1,0
887378,20000.0,11.99,10.000000,100000.00,good,0.0,15,1.0,0.0,110.0,...,0,0,0,0,0,0.000000,0.009091,3.006072,1,0

In [44]:
df_clean.columns

Index(['loan_amnt', 'int_rate', 'emp_length', 'annual_inc', 'loan_status',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'application_type',
       'acc_now_delinq', 'term_ 36 months', 'term_ 60 months', 'grade_A',
       'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G',
       'home_ownership_mortgage', 'home_ownership_others',
       'home_ownership_own', 'home_ownership_rent', 'purpose_car',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement', 'purpose_house',
       'purpose_major_purchase', 'purpose_medical', 'purpose_moving',
       'purpose_other', 'purpose_renewable_energy', 'purpose_small_business',
       'purpose_vacation', 'purpose_wedding',
       'inversed_mths_since_last_delinq', 'inversed_mths_since_last_record',
       'income_to_debt_ratio'],
      dtype='object')

In [47]:
pkl_filename= '/Users/xzhou/github/project_files/lending_club/loan.pkl'

with open(pkl_filename, 'wb') as pklfile:
    pickle.dump(df_clean, pklfile)